//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board_Events.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tcTaskDescribtion_SelectedIndex {
            get {
                return ((int)(this["tcTaskDescribtion_SelectedIndex"]));
            }
            set {
                this["tcTaskDescribtion_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bCheckTasksByStart {
            get {
                return ((bool)(this["bCheckTasksByStart"]));
            }
            set {
                this["bCheckTasksByStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int iMaxCheckThreads {
            get {
                return ((int)(this["iMaxCheckThreads"]));
            }
            set {
                this["iMaxCheckThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bAutoStartScheduler {
            get {
                return ((bool)(this["bAutoStartScheduler"]));
            }
            set {
                this["bAutoStartScheduler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShowTaskCheckingInXHE {
            get {
                return ((bool)(this["bShowTaskCheckingInXHE"]));
            }
            set {
                this["bShowTaskCheckingInXHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kareenpyros3ia@yandex.ru")]
        public string EMailFrom {
            get {
                return ((string)(this["EMailFrom"]));
            }
            set {
                this["EMailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qtn45jgL")]
        public string EmailFromPassword {
            get {
                return ((string)(this["EmailFromPassword"]));
            }
            set {
                this["EmailFromPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMailTo {
            get {
                return ((string)(this["EMailTo"]));
            }
            set {
                this["EMailTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendNewvariansEMailAfterTaskCheck {
            get {
                return ((bool)(this["SendNewvariansEMailAfterTaskCheck"]));
            }
            set {
                this["SendNewvariansEMailAfterTaskCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CalbackKillerPluginUrl {
            get {
                return ((string)(this["CalbackKillerPluginUrl"]));
            }
            set {
                this["CalbackKillerPluginUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowVariantCallRequestInXHE {
            get {
                return ((bool)(this["ShowVariantCallRequestInXHE"]));
            }
            set {
                this["ShowVariantCallRequestInXHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimesStartted {
            get {
                return ((bool)(this["FirstTimesStartted"]));
            }
            set {
                this["FirstTimesStartted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequestCallToNewVariants {
            get {
                return ((bool)(this["RequestCallToNewVariants"]));
            }
            set {
                this["RequestCallToNewVariants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelIndexSettingsPage {
            get {
                return ((int)(this["SelIndexSettingsPage"]));
            }
            set {
                this["SelIndexSettingsPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int splitTasksToResultsDistance {
            get {
                return ((int)(this["splitTasksToResultsDistance"]));
            }
            set {
                this["splitTasksToResultsDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public int splitResultsToResultDistance {
            get {
                return ((int)(this["splitResultsToResultDistance"]));
            }
            set {
                this["splitResultsToResultDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public int splitTaskResultsToLogDistance {
            get {
                return ((int)(this["splitTaskResultsToLogDistance"]));
            }
            set {
                this["splitTaskResultsToLogDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainSize {
            get {
                return ((global::System.Drawing.Size)(this["MainSize"]));
            }
            set {
                this["MainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddOnlyNewVariants {
            get {
                return ((bool)(this["AddOnlyNewVariants"]));
            }
            set {
                this["AddOnlyNewVariants"] = value;
            }
        }
    }
}
